---
directories:
    - /Users/matthieu/Desktop/recursive-movies
extensions:
    file:
        - mkv
        - avi
        - mp4
        - iso
        - img
        - lol
    directory:
        - dvd
download:
    posters: true
    trailers: true
